//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadorTabelas.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CriadorTabelas.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GifSAP {
            get {
                object obj = ResourceManager.GetObject("GifSAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        /// </summary>
        internal static System.Drawing.Icon Icone {
            get {
                object obj = ResourceManager.GetObject("Icone", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_de_usuario {
            get {
                object obj = ResourceManager.GetObject("login_de_usuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OIP {
            get {
                object obj = ResourceManager.GetObject("OIP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SAP_Business_One {
            get {
                object obj = ResourceManager.GetObject("SAP_Business_One", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREATE PROC SO_ExecutaAprovacao_proc
        ///@Pedido AS INT  
        ///,@Status AS NVARCHAR(1)  
        ///,@Usuario AS INT  
        ///,@Modelo AS NVARCHAR(254)
        ///,@DocType AS INT
        ///,@Etapa AS NVARCHAR(254)
        ///,@Texto As NVARCHAR(MAX) = NULL
        ///,@UserCode As NVARCHAR(MAX) = NULL
        ///											
        ///As  
        ///Begin  
        ///
        ///	IF (@UserCode IS NOT NULL)
        ///	BEGIN
        ///		SET @Usuario = (SELECT &quot;USERID&quot; FROM OUSR WHERE &quot;USER_CODE&quot; = @UserCode)
        ///	END
        ///  
        /// If (@Status = &apos;A&apos;)  
        ///    Begin  
        ///  
        ///	   Update [@SOAPROVPED]   
        ///	   Set   
        ///		 U_Autorizado = &apos;TRUE&apos;,  
        ///		 U_D [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SO_ExecutaAprovacao_proc {
            get {
                return ResourceManager.GetString("SO_ExecutaAprovacao_proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREATE PROC SO_Soluções       
        ///@object_type nvarchar(20),    -- SBO Object Type        
        ///@transaction_type nchar(1),   -- [A]dd, [U]pdate, [D]elete, [C]ancel, C[L]ose        
        ///@num_of_cols_in_key int,        
        ///@list_of_key_cols_tab_del nvarchar(255),        
        ///@list_of_cols_val_tab_del nvarchar(255),        
        ///@error int output,        
        ///@error_message nvarchar (200) output
        ///
        ///  
        ///
        ///
        ////*
        ///	Procedure utilizada no Add-on SO Solutions
        ///	Autor: Igor Oliveira	
        ///*/
        ///
        ///AS
        ///
        ///
        ///--/* Aprovação de Pedido - Documento d [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SO_Soluções {
            get {
                return ResourceManager.GetString("SO_Soluções", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trancar {
            get {
                object obj = ResourceManager.GetObject("trancar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
